### ISSUE TITLE
Create htcondor package on conda-forge

### ISSUE THREAD

**Issue by johanneskoester** [Snakemake-Profiles/htcondor#1]
For consistency, it would be great if htcondor could be installed via conda.

**Comment by jheuel** [comment]
I agree that it would be more consistent. However, HTCondor does not provide a source code package on PyPI, which is needed for conda-forge as far as I know.

**Comment by johanneskoester** [comment]
Mhm, good point. There is no general restriction in this regard on conda-forge (they also publish binaries as long as the license allows it). However, it might be bit less straightforward to create the package, as the conda skeleton pypi command indeed requires a source URL. There is https://anaconda.org/jasoncpatton/htcondor, which could serve as a template.

**Comment by dpmerrell** [comment]
Is this what you're looking for?

[https://anaconda.org/conda-forge/python-htcondor]()

Thanks for this repo, btw

**Comment by jheuel** [comment]
Exactly! Thanks!
