### ISSUE TITLE
`Schedd.transaction()` and `Schedd.queue()` deprecated

### ISSUE THREAD

**Issue by olantwin** [Snakemake-Profiles/htcondor#15]
The current way to interact with Schedd in grid-submit.py is deprecated:

```
FutureWarning: Schedd.transaction() was deprecated in version 10.7.0 and will be removed in a future release.  Use Schedd.submit() instead.
  warnings.warn(message, FutureWarning)
FutureWarning: Submit.queue() was deprecated in version 10.7.0 and will be removed in a future release.  Use Schedd.submit() instead.
  warnings.warn(message, FutureWarning)
```

I'd be happy to try fixing it, but this is the first time I touch the HTCondor python bindings, so might take a bit.

**Comment by jheuel** [comment]
Hi Oliver,
thanks for filing the issue. If you want to give it a try you can find some inspiration in the corresponding change in ganga: https://github.com/ganga-devs/ganga/pull/2182/files

**Comment by olantwin** [comment]
Thanks for the quick reply!

I think the change is rather trivial in that case. I'll quickly test and then open a PR.

I should probably open a separate issue for this, but is there a reason you didn't allow configuring the `MaxRuntime` and `JobFlavour`? Are they CERN specific?

**Comment by jheuel** [comment]
I think those are CERN specific. Beware that for CERN you need to add this for authentication:
```
# add kerberos credentials
col = htcondor.Collector()  # noqa: F841
credd = htcondor.Credd()
credd.add_user_cred(htcondor.CredTypes.Kerberos, None)
sub["MY.SendCredential"] = "True"
```

**Comment by olantwin** [comment]
> Beware that for CERN you need to add this for authentication:
> 
> ```
> # add kerberos credentials
> col = htcondor.Collector()  # noqa: F841
> credd = htcondor.Credd()
> credd.add_user_cred(htcondor.CredTypes.Kerberos, None)
> sub["MY.SendCredential"] = "True"
> ```

Thanks for the tip! It seems like this is not needed when submitting from lxplus, but I'll keep it in mind in case I want to submit from my local machine.
