### ISSUE TITLE
Format of "run:" statement with HTCondor profile 

### ISSUE THREAD

**Issue by YazBraimah** [Snakemake-Profiles/htcondor#2]
Hi Johannes,

Can you give an example of what a rule's "run:" statement should look like with this htcondor profile?

Thanks!

**Comment by jheuel** [comment]
Any regular Snakefile should do, for example:
```
rule all:
    input:
        'hostname1.txt',
        'hostname2.txt'

rule hostname1:
    output: 'hostname1.txt'
    shell: 'hostname > {output}'

rule hostname2:
    output: 'hostname2.txt'
    run:
        shell('hostname > {output}')
```

However, the profile assumes to have a shared file system between the cluster nodes and the submitting node.
If you need help, you may need to show what you tried and how it failed.

**Comment by YazBraimah** [comment]
I was running multi-line shell commands and attempting to move output files to a new location, that's why my job was failing. It's working now though, thanks for your input.
